### ISSUE TITLE
Cleaning Suggestions

### ISSUE THREAD

**Issue by tarvismk** [akrinaldi/ENG798_Museum_data_archive_project#1]
- What's up with the creation date being spread between three columns?
- Repeating Pieces or Titles -- make more specific?
- Cleaning up the medium tab? Should we make it all more straightforward? And easily read?
- Deleting some of the Columns? For instance: artist_id, classification (unless it feels like the medium does not do justice)
- So if we focus on Department and physical_location for the 'hidden' part of our research, what about the rest of the columns? How do we keep those as a part of the research? Would this have to entail making a few visualizations to show relations of those two with 'medium,' artist info, etc.?

**Comment by mfennessey** [comment]
-Since we are looking at what is on display and what is not, we should think about correlations between “physical_location” and other columns. I suggest that “medium,” “classification,” “nationality,” and “birthplace” might be interesting columns to compare against “physical_location.” Are some media more likely to be displayed? Are some nationalities privileged over others for display? 

-New question given the previous suggestion: should we aim to clean every column, or just the ones we are most interested in? As you suggest, I think we can delete some columns. Artist_ID can go. Perhaps “role” as well. We probably don’t need “Web URL” 

-Should we merge “Not on view” and “off-site” in the “physical_location” column?

-We might approach cleaning the medium tab by making up much broader categories. Just in the “not on view” category, there are 4633 different choices, so this would be a significant undertaking, and we would lose a fair amount of nuance. But we might want to separate it into broader categories like “painting,” “sculpture,” “book,” etc. These categories could correspond with the kinds of questions we want to ask. (Example: do we need to account for the difference between things like “brass” and “brass with traces of silvering”? Perhaps not.

-Under nationality, can we merge categories where a nationality is repeated (like “Japanese” and “Japanese|Japanese”)? This would mean losing the ability to differentiate between collaborative and single artist works. 

-I don’t understand what “creation_date_earliest” is telling us compared to “creation_date.” Do we need both of these columns?

**Comment by tarvismk** [comment]
Github is so fun, honestly lol

**Comment by tarvismk** [comment]
Okay, so like what do in the date column with things added/printed later? There also seem to be reprints every now and then. I will include an image of the leftovers near the end of this session.

**Comment by tarvismk** [comment]
BCE?? 56 items listed with negative years in the other two tabs

**Comment by tarvismk** [comment]
Consideration of the medium column: presence of the 'classification' tab (a norm in Museum Nomenclature) seems to be doing the broad medium strokes suggested by Michael. No answer, but just a consideration.

**Comment by tarvismk** [comment]
What do we think about the width, hieght, depth, and diameter? I remember that being one of the things that got me hooked on the set, and I think it could still be pretty important to keep. Perhaps another visualization?
